### ISSUE TITLE
MailerExporter Error

### ISSUE THREAD

**Issue by blackcoffee4u** [janreges/siteone-crawler#28]
Hallo Ján, 
first of all big thanks for this great crawler.
I am trying to set up the Mailer for several days but I always get stuck with:
If I leave the --mail-from Option empty:
"MailerExporter error: Invalid response to MAIL FROM command: 555 5.5.4 Unsupported option: Crawler"

Otherwise:
"MailerExporter error: Invalid response to MAIL FROM command: 555 5.5.4 Unsupported option: <d****v@f**-***.**>"

Example:
./crawler --url=https://p**-e**n.de --mail-to=m**s@f**-***.** --mail-from=d****v@f**-***.** --mail-from-name="M***DEV" --mail-subject-template="ReportSite" --mail-smtp-host=*****.kas**er.com --mail-smtp-port=25 --mail-smtp-user=d**@ff**-***.** --mail-smtp-pass=************

My Environment: 
Ubuntu 24.4 (Crawler as Git-Clone)
external SMTP Server (where Port 25 is listening and open)

I would like to run the crawler as a service to send my the results several times a week.

I would be thankful for any futher hint. 
Kind regards
Matthias

**Comment by janreges** [comment]
Hi @blackcoffee4u,

I'm glad you like the crawler :)

I'm not sure how to understand your sample command. I assume you were trying to obfuscate it.

But in principle, using the notation as in the documentation should work normally, example:

`--mail-smtp-host=your.mailserver.com --mail-to=target@domain.com --mail-from=john.wick@domain.com --mail-from-name="John Wick"`

**Comment by janreges** [comment]
Hi, @blackcoffee4u,

did my answer help you? Can we close this issue?

**Comment by janreges** [comment]
@blackcoffee4u, I assume that your mailer is already working after the last instruction. If not, please open a new issue - I'm closing this one.
