### ISSUE TITLE
Skipped URLs Reporting (-6:SKP)

### ISSUE THREAD

**Issue by GitHub-Mike** [janreges/siteone-crawler#34]
We need more detailed reports on the skipped URLs with the status -6:SKP. There are some URLs with this status that have been skipped, but I can't determine the reason.

There are 176 URLs, most of which contain a query string. Unfortunately, these are not listed under Skipped URLs.

There is also no recognisable pattern:

```
news?start
news?start=7
news?start=14
news?start=21
news?start=28
news?start=35
news?start=42 <-- -6:SKP
news?start=49 <-- -6:SKP
news?start=56 <-- -6:SKP
news?start=63
```

**Comment by janreges** [comment]
Hi @GitHub-Mike,

I already had to implement one anti-loop protection. On some sites there are badly generated dynamic links.

This protection works by continuously checking the "basename" of the URL (the last part without the query string), in your case "news". If the crawler finds more than 5 URLs ending in "news" that don't return a code of 200, then all other URLs ending in "news" are skipped.

I am thinking about how to include them among the skipped URLs. But there may be tens of thousands of them on some of the wrong sites.

**Comment by GitHub-Mike** [comment]
> I already had to implement one anti-loop protection. On some sites there are badly generated dynamic links.

OK, that's not a bad idea, but then there would have to be a whitelist for "good" URLs.

> This protection works by continuously checking the "basename" of the URL (the last part without the query string), in your case "news". If the crawler finds more than 5 URLs ending in "news" that don't return a code of 200, then all other URLs ending in "news" are skipped.

OK, then the first step could be to make the number configurable and/or the functionality deactivatable.

> I am thinking about how to include them among the skipped URLs. But there may be tens of thousands of them on some of the wrong sites.

We then leave the protection activated as the default setting and give the option of "relaxing" the protection.

**Comment by janreges** [comment]
Hi @GitHub-Mike,

as a compromise, you will find in the current version in the main branch the option `--max-non200-responses-per-basename` added with a default value of `5`. You can increase this to any higher number.

Btw, if the URL is being skipped for this reason, you will find a NOTICE in the report and its summary: `URL '/news' ignored because there are too many (>= 5) non-200 URLs with same basename.`

Please test and close the ticket if is OK.

**Comment by GitHub-Mike** [comment]
OK, thanks for the quick solution. I made 2 runs because I had set the value to 200 the first time and that was not enough. At 250 all URLs were retrieved. I also excluded URLs with the query string rCH=2, as this is a cookie functionality that is no longer required.

I think we can close the issue.
