### ISSUE TITLE
External scripts

### ISSUE THREAD

**Issue by GitHub-Mike** [janreges/siteone-crawler#37]
I noticed that at the beginning of the head section of the Joomla test project some external script tags and also an inline script from Google TagManager are missing. This is also not a side effect of #30, as this was already the case in the version of 06.12.2024.

Web:

```html
<head>
<script async="" src="https://connect.facebook.net/en_US/fbevents.js"></script>
<script async="" src="//www.google-analytics.com/analytics.js"></script>
<script async="" src="//www.googletagmanager.com/gtm.js?id=GTM-XXXXXXX"></script>
<script>window.dataLayer = window.dataLayer || [];</script>
<!-- Google Tag Manager JS V.1.0.2 from Tools for Joomla -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-XXXXXXX');</script>
<!-- End Google Tag Manager JS -->
```

Local:

```html
<head>
<script>window.dataLayer = window.dataLayer || [];</script>
<!-- Google Tag Manager JS V.1.0.2 from Tools for Joomla -->

<!-- End Google Tag Manager JS -->
```

```--allowed-domain-for-external-files='*.example.com'``` was used.
```--disable-javascript``` has _not_ been used.

If the tool should also work for the creation of static websites and not only for local offline versions, it would make sense to create a possibility to leave the code for the integration of external files selectively in the code, but also not to download it.

Perhaps with parameters like these:
```--do-not-touch-domain-for-external-files='connect.facebook.net'```?
```--do-not-touch-regex-for-external-files='/^\/en_US\/.*$/i'```

We should ensure that the relevant parameters are standardised. There is perhaps already something inconsistent.

```
--allowed-domain-...  : permitted subdomain.domain.tld

What is the order of conflicts here?
--ignore-regex-...    : path/filename/query/fragment do not crawl
--include-regex-...   : path/filename/query/fragment crawl

--regex-filtering-... : the same as --include-regex-..., but a different name?
```

It might have been better to use something like this in general: allow/disallow or allow/deny instead of include/ignore and then use ignore if URLs in the source code are to be ignored. But with subsequent parameter renaming it's one of those things.

What do you think?

**Comment by janreges** [comment]
Hi @GitHub-Mike,

there is an update in the main branch that you can set `--offline-export-remove-unwanted-code=1/0` to remove code that is unwanted for the offline version - typically embedding analytics, social networks, cookie consent, etc. You want to set it to `0`. Default is `1`.

**Comment by GitHub-Mike** [comment]
OK, thank you. I did another run last night with the new parameter and the scripts were not removed. I think we can close the issue.
