### ISSUE TITLE
SiteOne Crawler is damaged and can't be opened (mac os, 14.1.1)

### ISSUE THREAD

**Issue by janhenckens** [janreges/siteone-crawler#5]
Running the Mac app for the first time shows me this error message:

![Screenshot 20231209-085916-hGTsK3Oa@2x](https://github.com/janreges/siteone-crawler/assets/755428/55980895-c5ff-4d26-a33a-10123a8d5702)

I'm on an M1 running 14.1.1
![Screenshot 20231209-085945-HSlxJyEr@2x](https://github.com/janreges/siteone-crawler/assets/755428/cf2cee35-8a23-4eb7-ba1e-96a94c928472)

I downloaded the version currently linked on the website (SiteOne-Crawler-mac-arm64-1.0.6.dmg).

**Comment by janreges** [comment]
Hi @janhenckens,

thank you for issue report.

I found out that this is an issue related to the DMG not being signed by an official paid Apple developer account. I'm already dealing with Apple support - their payment gateway is rejecting my payment, I don't know why. The next release I believe will be able to sign the release.

Until then, please proceed as follows:

- Install the DMG again, but don't run the application yet
- Run command `sudo xattr -cr /Applications/SiteOne\ Crawler.app`
- Run the application

Please confirm if it works fine. Thank you.

**Comment by janreges** [comment]
Hi, I'm closing this ticket.

The current GUI version for macOS x64/arm64 is already signed and notarized by Apple, so it is no longer necessary to run the command mentioned in the previous comment.
