### ISSUE TITLE
./crawler: line 16: ./bin/swoole-cli: cannot execute binary file

### ISSUE THREAD

**Issue by justinholtweb** [janreges/siteone-crawler#6]
When attempting a crawl on the siteone-crawler-v1.0.6-linux-x64 version, I get this error:

`./crawler: line 16: ./bin/swoole-cli: cannot execute binary file`

**Comment by janreges** [comment]
Hi @justinholtweb,

Thank you for issue report.

Could you please provide output of these commands executed from crawler root directory?

- `stat ./bin/swoole-cli` 
- `lsb_release -a` 
- `uname -a` ?

**Comment by justinholtweb** [comment]
- `stat ./bin/swoole-cli` --> `16777234 975860688 -rwxr----x 1 jholt staff 0 68954472 "Dec 11 11:52:37 2023" "Apr 26 07:16:16 2023" "Dec 11 11:52:37 2023" "Apr 26 07:16:16 2023" 4096 134680 0 ./bin/swoole-cl`
- `lsb_release -a` --> `zsh: command not found: lsb_release`
- `uname -a` --> `Darwin MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Oct  4 23:56:02 PDT 2023; root:xnu-8020.240.18.704.15~1/RELEASE_ARM64_T6000 arm64`

**Comment by janreges** [comment]
Aaaa, Thank you, that explains it.

You have to use build for macOS and also for arm64 architecture, not x64.

This is build for you: https://github.com/janreges/siteone-crawler/releases/download/v1.0.6/siteone-crawler-v1.0.6-macos-arm64.tar.gz

Btw, you can try this command-line version, of course, but I recommend you also desktop application for macOS, see https://crawler.siteone.io/getting-started/quick-start-guide/

In the following hours, I will also ensure that the application is signed with a Apple Developer certificate - until then, it is necessary to run the `sudo xattr -cr /Applications/SiteOne\ Crawler.app` command once between installation and the first start, as it is also written in the documentation.

Please let me know if it works for you.

**Comment by justinholtweb** [comment]
Oh gosh sorry thought that was the one I was installing. In the meantime, I did get the desktop app working and running. Thank you.
